package sshdcfg

import (
	"bytes"
	"fmt"
	"strings"
	"time"
)

// Render serializes a DropIn back to bytes. For Directives whose RawLine is
// set (i.e. those originating from a parse), the RawLine is emitted verbatim
// (with the trailing newline appended). For NEW Directives (RawLine == ""),
// a canonical-format line is emitted: 4-space indent inside Match blocks per
// OpenSSH style; no indent at top level.
//
// The Match block header is ALWAYS emitted in canonical form (`Match ` +
// Condition) — this is a deliberate one-character normalization that strips
// redundant whitespace authored by humans (e.g. `Match  Group X` with two
// spaces becomes `Match Group X`). Admins who used multi-space separators
// will see a one-byte cosmetic diff on first apply via M-APPLY-SETUP; the
// SUMMARY documents this as N-03. Alternative (RawHeader on MatchBlock) is
// future polish if the cosmetic diff proves annoying in practice.
//
// Order: top-level Directives FIRST, then Match blocks. This matters per
// pitfall A3 / D-16 (sshd_config(5) "a Match block continues until the next
// Match directive or the end of the file") — putting top-level directives
// after a Match block scopes them to that Match block. The Phase 3 D-07
// canonical template intentionally has zero top-level directives, but
// USER-13 / D-16 will add `PasswordAuthentication no` at top level above the
// Match block via this writer.
func Render(d DropIn) []byte {
	var b bytes.Buffer
	for _, dir := range d.Directives {
		emitDirective(&b, dir, false)
	}
	for _, m := range d.Matches {
		// Match header always emitted in canonical form (single space).
		// See package doc for the rationale and SUMMARY for the known
		// one-byte diff against multi-space admin-authored Match lines.
		fmt.Fprintf(&b, "Match %s\n", m.Condition)
		for _, dir := range m.Body {
			emitDirective(&b, dir, true)
		}
	}
	return b.Bytes()
}

// emitDirective writes a single Directive line to b. If d.RawLine is set, the
// original line is emitted byte-for-byte (with a trailing newline). Otherwise
// a canonical-format line is generated: 4-space indent if `indented` is true
// (i.e. inside a Match block), no indent at top level.
func emitDirective(b *bytes.Buffer, d Directive, indented bool) {
	if d.RawLine != "" {
		// Byte-identity path — emit the original line as parsed, append the
		// LF that bufio.Scanner stripped during the read.
		b.WriteString(d.RawLine)
		b.WriteByte('\n')
		return
	}
	if indented {
		b.WriteString("    ") // OpenSSH canonical 4-space inside Match blocks
	}
	b.WriteString(d.Keyword)
	if d.Value != "" {
		b.WriteByte(' ')
		b.WriteString(d.Value)
	}
	b.WriteByte('\n')
}

// CanonicalDropIn returns the D-07 canonical drop-in pre-rendered with the
// "Last applied: <ISO timestamp>" header. chrootRoot is interpolated literally
// per D-08 (NOT %h — the literal path keeps sshd_config as the single source
// of truth for the chroot root). Trailing slashes on chrootRoot are stripped
// before interpolation so the output never contains a double slash before %u.
//
// The output is byte-stable for a fixed (chrootRoot, applied) pair —
// golden-file tests in render_test.go pin the exact bytes via
// internal/sshdcfg/testdata/canonical-drop-in.golden.
func CanonicalDropIn(chrootRoot string, applied time.Time) []byte {
	chrootRoot = strings.TrimRight(chrootRoot, "/")
	return []byte(fmt.Sprintf(`# Generated by sftp-jailer. Do not edit by hand — run %csftp-jailer%c to modify.
# Last applied: %s

Match Group sftp-jailer
    ChrootDirectory %s/%%u
    ForceCommand internal-sftp -f AUTHPRIV -l INFO
    AllowTcpForwarding no
    X11Forwarding no
    PermitTunnel no
`, '`', '`', applied.UTC().Format(time.RFC3339), chrootRoot))
}
